### ISSUE TITLE
Simulator crashes on launch

### ISSUE THREAD

**Issue by Davt2000** [hydronautics-team/simulator#7]
после билда при попытке запуска через start_simulation.bash симулятор крашится на запуске
```
$ bash start_simulation.bash 
Traceback (most recent call last):
  File "bottom_obj.py", line 11, in <module>
    my_file.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
TypeError: can only concatenate list (not "float") to list
... logging to /home/maharius/.ros/log/549eeae2-3511-11ed-ac1f-f73bffe4c51d/roslaunch-Terra-13070.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: while processing /home/maharius/hydronautics_code/simulator/src/auv_gazebo/launch/bottom_objects.launch:
Invalid roslaunch XML syntax: no element found: line 1, column 0
The traceback for the exception was written to the log file
```

log file attached
[roslaunch-Terra-14196.log](https://github.com/hydronautics-team/simulator/files/9577168/roslaunch-Terra-14196.log)

**Comment by khosta77** [comment]
Исправил ошибку в рандомайзере. Метод random.sample() возращает список, оказывается...
Вот правда я столкнулся с тем что желтые столбы на новых положениях после него оказываются упавшими. Вот уже эта ошибка откуда появляется я затрудняюсь ответить.

**Comment by khosta77** [comment]
> после билда при попытке запуска через start_simulation.bash симулятор крашится на запуске
> 
> ```
> $ bash start_simulation.bash 
> Traceback (most recent call last):
>   File "bottom_obj.py", line 11, in <module>
>     my_file.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
> TypeError: can only concatenate list (not "float") to list
> ... logging to /home/maharius/.ros/log/549eeae2-3511-11ed-ac1f-f73bffe4c51d/roslaunch-Terra-13070.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> RLException: while processing /home/maharius/hydronautics_code/simulator/src/auv_gazebo/launch/bottom_objects.launch:
> Invalid roslaunch XML syntax: no element found: line 1, column 0
> The traceback for the exception was written to the log file
> ```
> 
> log file attached [roslaunch-Terra-14196.log](https://github.com/hydronautics-team/simulator/files/9577168/roslaunch-Terra-14196.log)

**Comment by khosta77** [comment]
> после билда при попытке запуска через start_simulation.bash симулятор крашится на запуске
> 
> ```
> $ bash start_simulation.bash 
> Traceback (most recent call last):
>   File "bottom_obj.py", line 11, in <module>
>     my_file.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
> TypeError: can only concatenate list (not "float") to list
> ... logging to /home/maharius/.ros/log/549eeae2-3511-11ed-ac1f-f73bffe4c51d/roslaunch-Terra-13070.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> RLException: while processing /home/maharius/hydronautics_code/simulator/src/auv_gazebo/launch/bottom_objects.launch:
> Invalid roslaunch XML syntax: no element found: line 1, column 0
> The traceback for the exception was written to the log file
> ```
> 
> log file attached [roslaunch-Terra-14196.log](https://github.com/hydronautics-team/simulator/files/9577168/roslaunch-Terra-14196.log)

Исправил ошибку в рандомайзере. Метод random.sample() возращает список, оказывается...
Вот правда я столкнулся с тем что желтые столбы на новых положениях после него оказываются упавшими. Вот уже эта ошибка откуда появляется я затрудняюсь ответить. Добавил пул реквест.
